# RDF.sub -- submit the XGDC.py file

executable              = XGDC.sh

log                     = XGDC.log
output                  = XGDC.out
error                   = XGDC.err

should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

request_cpus            = 1
request_memory          = 5G
request_disk            = 5G

+UseOS                  = "el9"
## This job can run up to 4 hours. Can choose "express", "short", "medium", or "long".
+JobCategory            = "medium"


queue